"""Generate the repository README from the website's documentation page."""
import argparse
from dataclasses import dataclass, field
from html.parser import HTMLParser
from pathlib import Path
import re
from urllib.parse import urljoin

ROOT = Path(__file__).resolve().parents[1]
DOCUMENTATION = 'https://rendezvous.sh/docs'


@dataclass
class Element:
    tag: str
    attrs: dict = field(default_factory=dict)
    children: list = field(default_factory=list)


class DocumentationParser(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.main = None
        self.stack = []

    def handle_starttag(self, tag, attrs):
        if tag == 'main':
            if self.main is not None:
                raise ValueError('Expected one documentation main element')
            self.main = Element(tag, dict(attrs))
            self.stack = [self.main]
        elif self.stack:
            node = Element(tag, dict(attrs))
            self.stack[-1].children.append(node)
            if tag not in {'br', 'hr'}:
                self.stack.append(node)

    def handle_endtag(self, tag):
        if self.stack and tag not in {'br', 'hr'}:
            if self.stack[-1].tag != tag:
                raise ValueError(f'Unbalanced documentation element: {tag}')
            self.stack.pop()

    def handle_data(self, data):
        if self.stack:
            self.stack[-1].children.append(data)


def text(node):
    return node if isinstance(node, str) else ''.join(text(child) for child in node.children)


def markdown(node):
    if isinstance(node, str):
        value = re.sub(r'\s+', ' ', node)
        return re.sub(r'([\\`*_\[\]<>])', r'\\\1', value)
    if node.tag == 'pre':
        value = text(node).strip('\n')
        fence = '`' * max(3, max((len(run) + 1 for run in re.findall(r'`+', value)), default=0))
        language = 'sh' if value.startswith('curl ') else 'text'
        return f'\n\n{fence}{language}\n{value}\n{fence}\n\n'
    if node.tag == 'code':
        value = text(node)
        fence = '`' * max(1, max((len(run) + 1 for run in re.findall(r'`+', value)), default=0))
        return f'{fence}{value}{fence}'
    if node.tag == 'main':
        return '\n\n'.join(markdown(child).strip() for child in node.children
                           if not isinstance(child, str) or child.strip())
    if node.tag == 'ul':
        return '\n\n' + '\n'.join(markdown(child).strip() for child in node.children
                                   if not isinstance(child, str) or child.strip()) + '\n\n'
    contents = ''.join(markdown(child) for child in node.children)
    if node.tag in {'h1', 'h2', 'h3', 'h4', 'h5'}:
        return '\n\n' + '#' * (int(node.tag[1]) + 1) + ' ' + contents.strip() + '\n\n'
    if node.tag == 'p':
        return '\n\n' + contents.strip() + '\n\n'
    if node.tag == 'li':
        return '- ' + contents.strip() + '\n'
    if node.tag in {'strong', 'b'}:
        return '**' + contents + '**'
    if node.tag in {'em', 'i'}:
        return '*' + contents + '*'
    if node.tag == 'a':
        return f'[{contents}]({urljoin(DOCUMENTATION, node.attrs["href"])})'
    if node.tag == 'br':
        return '  \n'
    if node.tag == 'hr':
        return '\n\n---\n\n'
    if node.tag == 'span':
        return contents
    raise ValueError(f'Unsupported documentation element: {node.tag}')


def render(documentation):
    parser = DocumentationParser()
    parser.feed(documentation)
    parser.close()
    if parser.main is None or parser.stack:
        raise ValueError('Missing or incomplete documentation main element')
    body = markdown(parser.main).strip()
    return '''<!-- Generated by tools/build_readme.py from public/docs.html. Edit the website documentation, then regenerate. -->
# Rendezvous

[Website](https://rendezvous.sh) · [Documentation](https://rendezvous.sh/docs) · [CLI reference](https://rendezvous.sh/cli) · [Security](https://rendezvous.sh/security) · [Releases](https://github.com/rdzv/rendezvous/releases)

''' + body + '''

---

For source development, builds, testing, and publication, see [BUILD.md](BUILD.md).
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = render((ROOT / 'public/docs.html').read_text())
    target = ROOT / 'README.md'
    if args.check:
        if target.read_text() != expected:
            raise SystemExit('README.md is stale; run python3 tools/build_readme.py')
        print('README matches the website documentation')
    else:
        target.write_text(expected)
        print('Generated README.md from public/docs.html')


if __name__ == '__main__':
    main()
